const mockAlarms = [
  {
    WatcherID: {value: 0},
    acknowledged: {value: false},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 4},
    mutedBy: {value: ""},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake1"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity, Commanded severity, Commanded severity, Commanded severity, Commanded severity, Commanded severity, Commanded severity, Commanded severity, Commanded severity, Commanded severity"},
    severity: {value: 4},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: true},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 4},
    mutedBy: {value: ""},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake2"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sit amet eros sed erat elementum fermentum et nec ipsum. Etiam non ultrices tellus. Pellentesque risus nisi, gravida eu odio et, sodales mattis ex. Curabitur nisi tellus, porttitor vitae sagittis luctus, blandit quis erat. Mauris varius dignissim fringilla. Donec eleifend fermentum tellus et ullamcorper. Pellentesque sit amet auctor lorem. Praesent dictum nunc id neque molestie, sed commodo libero sollicitudin. Pellentesque iaculis tortor a turpis aliquam, et iaculis arcu iaculis.

Donec consequat felis ac mi scelerisque feugiat. In malesuada elementum enim, eget pharetra turpis ultricies ut. Nunc vestibulum sapien non orci feugiat, nec iaculis sapien convallis. Nunc placerat ante id suscipit malesuada. Fusce ac imperdiet tortor. Mauris ultrices velit eros, eu vulputate erat interdum vel. Aenean faucibus velit nec nibh semper dignissim. Proin luctus nulla elit, a dictum nisl dapibus pellentesque. Suspendisse semper erat ut eros elementum, id fermentum odio sagittis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce quis neque nibh. Vestibulum ultricies urna felis, vitae pharetra velit lobortis et. Etiam sodales eget orci quis lobortis.

Nam sit amet orci felis. Pellentesque ut mattis est. Cras at sollicitudin justo. Praesent at aliquam ligula, non facilisis lectus. Donec velit est, lobortis vitae malesuada eu, maximus id mi. Sed ut quam at sem pulvinar tincidunt. Fusce rhoncus eget metus at pulvinar. Praesent augue urna, egestas quis magna quis, dignissim semper nunc. Nunc semper faucibus convallis. Fusce sit amet quam tempus, congue tortor vitae, imperdiet leo.

Fusce vel pretium lorem. Sed quis posuere velit. Proin eget blandit augue, sit amet faucibus quam. Sed venenatis, sem sit amet varius mollis, turpis mi suscipit lorem, sed semper massa nibh ut tellus. Duis lacinia nisi sit amet arcu euismod, et facilisis lacus malesuada. Ut lorem risus, feugiat a nisl vel, commodo iaculis mauris. Aenean vel nunc at tellus convallis interdum. Donec sit amet vestibulum mauris. Sed ultrices ornare eros, sit amet vehicula eros ultrices ac. Aenean ut commodo massa. In lobortis eros libero, vitae sodales arcu mollis at. Quisque sodales rutrum mi, in pulvinar dolor bibendum sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam vitae accumsan dui. Ut id dapibus massa.

Sed pretium dictum lobortis. Aliquam purus diam, tristique a metus nec, tempor lacinia magna. Proin at enim et urna congue aliquam quis id nisi. Vestibulum sem velit, pellentesque eget dui sit amet, rhoncus scelerisque mauris. Ut ullamcorper eget est et elementum. Aliquam efficitur magna in libero cursus, eu dignissim quam gravida. Pellentesque tincidunt feugiat mi, in venenatis nulla accumsan id. Praesent vel eros non nisi lacinia luctus eget nec nisi. Sed pharetra nulla eu aliquet malesuada. Mauris quis ipsum in neque ultrices imperdiet pharetra quis lorem. Vestibulum tincidunt arcu in magna varius volutpat quis ut sem. Sed nulla purus, luctus et magna et, sagittis luctus metus. In lobortis dui vitae efficitur dignissim. Morbi dapibus, massa non volutpat semper, massa risus convallis risus, ac lobortis velit sapien ac lacus.`},
    severity: {value: 3},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: true},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 3},
    mutedBy: {value: ""},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake3"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 2},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: true},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 3},
    mutedBy: {value: "FakeUser"},
    mutedSeverity: {value: 3},
    name: {value: "test.Fake4-Muted"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 2},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: true},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 3},
    mutedBy: {value: ""},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake5"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 2},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: true},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 3},
    mutedBy: {value: "FakeUser"},
    mutedSeverity: {value: 3},
    name: {value: "test.Fake6-Muted"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 2},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: true},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 3},
    mutedBy: {value: ""},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake7"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 2},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: true},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 3},
    mutedBy: {value: ""},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake8"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 2},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: true},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 3},
    mutedBy: {value: ""},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake9"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 2},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: true},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 3},
    mutedBy: {value: ""},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake10"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 2},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: false},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 3},
    mutedBy: {value: ""},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake11"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 2},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: false},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 3},
    mutedBy: {value: ""},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake12"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 2},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: false},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 3},
    mutedBy: {value: "FakeUser"},
    mutedSeverity: {value: 3},
    name: {value: "test.Fake13-Muted"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 2},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: false},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 3},
    mutedBy: {value: ""},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake14"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 2},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: true},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 3},
    mutedBy: {value: ""},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake15"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 2},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: true},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 4},
    mutedBy: {value: "FakeUser"},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake16-Muted"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 3},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: false},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 4},
    mutedBy: {value: "FakeUser"},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake17-Muted"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 3},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: true},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 4},
    mutedBy: {value: "FakeUser"},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake18-Muted"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 4},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
  {
    WatcherID: {value: 0},
    acknowledged: {value: false},
    acknowledgedBy: {value: ""},
    escalateTo: {value: ""},
    escalated: {value: false},
    maxSeverity: {value: 4},
    mutedBy: {value: "FakeUser"},
    mutedSeverity: {value: 1},
    name: {value: "test.Fake19-Muted"},
    priority: {value: 0},
    private_host: {value: 1362406774},
    private_origin: {value: 79},
    private_rcvStamp: {value: 1574193720.7326922},
    private_revCode: {value: "ebe18429"},
    private_seqNum: {value: 157},
    private_sndStamp: {value: 1574193720.7318604},
    reason: {value: "Commanded severity"},
    severity: {value: 4},
    timestampAcknowledged: {value: 0},
    timestampAutoAcknowledge: {value: 0},
    timestampAutoUnacknowledge: {value: 0},
    timestampEscalate: {value: 0},
    timestampMaxSeverity: {value: 1574193664},
    timestampSeverityNewest: {value: 1574193664},
    timestampSeverityOldest: {value: 1574193664},
    timestampUnmute: {value: 0},
  },
];

export default mockAlarms;
