FROM node:10.16-alpine as builder

WORKDIR /usr/src/love

# Install and cache app dependencies
COPY love/package.json .
COPY love/yarn.lock .
RUN yarn install

COPY love .
COPY run_tests.sh .

CMD ["sh", "/usr/src/love/run_tests.sh"]