FROM node:10.15-alpine as builder

WORKDIR /usr/src/love

# Add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/love/node_modules/.bin:$PATH

# Install and cache app dependencies
COPY love/package.json .
COPY love/package-lock.json .
COPY love/yarn.lock .
RUN npm install

# Define url for the websockets host
ARG WEBSOCKET_HOST=127.0.0.1
ENV REACT_APP_WEBSOCKET_HOST=$WEBSOCKET_HOST

# Expose port
EXPOSE 3000

# Run development server in runtime
CMD npm start
