import React, { Component } from 'react';
import PropTypes from 'prop-types';
import PlayIcon from 'components/icons/MicsIcon/Play/PlayIcon';
import DownloadIcon from 'components/icons/MicsIcon/Download/DownloadIcon';
import PauseIcon from 'components/icons/MicsIcon/Pause/PauseIcon';
import styles from './DrawerMic.module.css';

export default class Record extends Component {
  static propTypes = {
    /**
     * The url blob generated by the record
     */
    url: PropTypes.string,
    /**
     * The name file set to the record
     */
    nameFile: PropTypes.string,
  };

  constructor(props) {
    super(props);
    this.state = {
      play: false,
    };
    this.aCtx;
    this.source;
    this.songSource;
    this.masterGain;
  }

  componentDidMount = () => {
    this.aCtx = new AudioContext();
    this.source = new Audio(this.props.url);
    this.songSource = this.aCtx.createMediaElementSource(this.source);
    this.masterGain = this.aCtx.createGain();
    this.masterGain.gain.value = 1;
    this.songSource.connect(this.masterGain);
    this.masterGain.connect(this.aCtx.destination);
  };

  componentWillUnmount = () => {
    if (this.state.play) this.play();
  };

  /**
   * Function to play the record
   */
  play = () => {
    let { aCtx, source } = this;
    if (this.state.play) {
      source.pause();
      this.setState({ play: false });
    } else {
      aCtx.resume();
      source.play();
      this.setState({ play: true });
    }
  };

  render() {
    const { url, nameFile, blob } = this.props;
    const svgPLay = this.state.play ? (
      <PauseIcon className={styles.playSVG}/>
    ) : (
      <PlayIcon className={styles.playSVG}/>
    );

    return (
      <div className={styles.records}>
        <span onClick={() => this.play()} className={[styles.recSpan, styles.marginBlock].join(' ')}>
          {svgPLay}
        </span>
        <span className={styles.spanNameFiles}>{nameFile}</span>
        <a onClick={() => this.auxFunc(blob)} href={url} download={nameFile} className={styles.download}>
          <DownloadIcon className={styles.downloadSvg}/>
        </a>
      </div>
    );
  }
}
