FROM node:16.13.2-alpine as builder

WORKDIR /usr/src/love

# Install and cache app dependencies
COPY love/package.json .
COPY love/yarn.lock .
RUN yarn install

RUN chown -R node:node node_modules

COPY love .
COPY docker/run-tests.sh .

CMD ["/usr/src/love/run-tests.sh"]
