FROM node:12.16.1-alpine as builder

WORKDIR /usr/src/love

# Install and cache app dependencies
COPY love/package.json .
COPY love/yarn.lock .
RUN yarn install

COPY love .
COPY docker/run-tests.sh .

CMD ["/usr/src/love/run-tests.sh"]
