FROM node:16.13.2-alpine as builder

# Set working directory
WORKDIR /usr/src/love

# Install and cache app dependencies
COPY love/package.json .
COPY love/yarn.lock .
RUN yarn install

# Change ownership of node_modules folder to avoid permission errors
RUN chown -R node:node /usr/src/love/node_modules

# Expose port
EXPOSE 3000

# Run development server in runtime
CMD yarn start
