FROM node:16-alpine3.16 as builder

# Set working directory
WORKDIR /usr/src/love

# Install and cache app dependencies
COPY love/package.json .
COPY love/yarn.lock .
RUN yarn install

# Expose port
EXPOSE 3000

# Run development server in runtime
CMD yarn start
