FROM node:12.16.1-alpine as builder

WORKDIR /usr/src/

# Install and cache app dependencies
COPY love/ local/

WORKDIR /usr/src/local/

RUN yarn install

WORKDIR /usr/src/love/love/

# Expose port
EXPOSE 3000

# Run development server in runtime
CMD cp -a /usr/src/local/* /usr/src/love/love; yarn start
