/** 
This file is part of LOVE-frontend.

Copyright (c) 2023 Inria Chile.

Developed by Inria Chile.

This program is free software: you can redistribute it and/or modify it under 
the terms of the GNU General Public License as published by the Free Software 
Foundation, either version 3 of the License, or at your option) any later version.

This program is distributed in the hope that it will be useful,but WITHOUT ANY
 WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
 A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with 
this program. If not, see <http://www.gnu.org/licenses/>.
*/

export const REQUEST_TOKEN = 'REQUEST_TOKEN';
export const RECEIVE_TOKEN = 'RECEIVE_TOKEN';
export const REQUEST_REMOVE_TOKEN = 'REQUEST_REMOVE_TOKEN';
export const REMOVE_REMOTE_TOKEN = 'REMOVE_REMOTE_TOKEN';
export const REJECT_TOKEN = 'REJECT_TOKEN';
export const EMPTY_TOKEN = 'EMPTY_TOKEN';
export const EXPIRE_TOKEN = 'EXPIRE_TOKEN';
export const MARK_ERROR_TOKEN = 'MARK_ERROR_TOKEN';
export const MARK_ERROR_REMOVE_TOKEN = 'MARK_ERROR_REMOVE_TOKEN';
export const GET_TOKEN_FROM_LOCALSTORAGE = 'GET_TOKEN_FROM_LOCALSTORAGE';

export const REQUEST_SWAP_TOKEN = 'REQUEST_SWAP_TOKEN';
export const RECEIVE_SWAP_TOKEN = 'RECEIVE_SWAP_TOKEN';
export const REJECT_SWAP_TOKEN = 'REJECT_SWAP_TOKEN';
export const MARK_ERROR_SWAP_TOKEN = 'MARK_ERROR_SWAP_TOKEN';
export const REQUIRE_SWAP_TOKEN = 'REQUIRE_SWAP_TOKEN';
export const CANCEL_SWAP_TOKEN = 'CANCEL_SWAP_TOKEN';
export const RECEIVE_CONFIG = 'RECEIVE_CONFIG';

export const OPEN_WS_CONNECTION = 'START_WS_CONNECTION';
export const CHANGE_WS_STATE = 'CHANGE_WS_STATE';
export const ADD_GROUP = 'ADD_GROUP';
export const REMOVE_GROUP = 'REMOVE_GROUP';
export const REQUEST_SUBSCRIPTIONS = 'REQUEST_SUBSCRIPTIONS';
export const REQUEST_GROUP_UNSUBSCRIPTION = 'REQUEST_GROUP_UNSUBSCRIPTION';
export const RECEIVE_GROUP_CONFIRMATION_MESSAGE = 'RECEIVE_GROUP_CONFIRMATION_MESSAGE';
export const RECEIVE_GROUP_UNSUBSCRIPTION_CONFIRMATION = 'RECEIVE_GROUP_UNSUBSCRIPTION_CONFIRMATION';
export const RESET_SUBSCRIPTIONS = 'RESET_SUBSCRIPTIONS';
export const RECEIVE_GROUP_SUBSCRIPTION_DATA = 'RECEIVE_GROUP_SUBSCRIPTION_DATA';
export const UPDATE_LAST_SAL_COMMAND = 'UPDATE_LAST_SAL_COMMAND';
export const UPDATE_LAST_SAL_COMMAND_STATUS = 'UPDATE_LAST_SAL_COMMAND_STATUS';

export const RECEIVE_IMAGE_SEQUENCE_DATA = 'RECEIVE_IMAGE_SEQUENCE_DATA';
export const RECEIVE_CAMERA_STATE_DATA = 'RECEIVE_CAMERA_STATE_DATA';
export const RECEIVE_READOUT_DATA = 'RECEIVE_READOUT_DATA';

export const UPDATE_SCRIPT_HEARTBEAT = 'UPDATE_SCRIPT_HEARTBEAT';
export const REMOVE_SCRIPTS_HEARTBEATS = 'REMOVE_SCRIPTS_HEARTBEATS';
export const UPDATE_CSC_HEARTBEATS = 'UPDATE_CSC_HEARTBEATS';
export const RECEIVE_HEARTBEAT_INFO = 'RECEIVE_HEARTBEAT_INFO';

export const UPDATE_LOG_MESSAGE_DATA = 'UPDATE_LOG_MESSAGE_DATA';
export const REMOVE_CSC_LOG_MESSAGES = 'REMOVE_CSC_LOG_MESSAGES';
export const UPDATE_ERROR_CODE_DATA = 'UPDATE_ERROR_CODE_DATA';
export const REMOVE_CSC_ERROR_CODE_DATA = 'REMOVE_CSC_ERROR_CODE_DATA';

export const RECEIVE_ALARM = 'RECEIVE_ALARM';
export const RECEIVE_ALL_ALARMS = 'RECEIVE_ALL_ALARMS';

export const RECEIVE_WORKSPACES = 'RECEIVE_WORKSPACES';
export const RECEIVE_WORKSPACES_ERROR = 'RECEIVE_WORKSPACES_ERROR';
export const RECEIVE_CURRENT_WORKSPACE = 'RECEIVE_CURRENT_WORKSPACE';

export const LOADING_VIEWS = 'LOADING_VIEWS';
export const RECEIVE_VIEWS = 'RECEIVE_VIEWS';
export const RECEIVE_VIEWS_ERROR = 'RECEIVE_VIEWS_ERROR';
export const RECEIVE_VIEW = 'RECEIVE_VIEW';
export const UPDATE_EDITED_VIEW = 'UPDATE_EDITED_VIEW';
export const CLEAR_EDITED_VIEW = 'CLEAR_EDITED_VIEW';
export const LOAD_EDITED_VIEW = 'LOAD_EDITED_VIEW';
export const SAVING_EDITED_VIEW = 'SAVING_EDITED_VIEW';
export const SAVE_ERROR = 'SAVE_ERROR';
export const SAVED_EDITED_VIEW = 'SAVED_EDITED_VIEW';
export const CHANGE_MODE = 'CHANGE_MODE';

export const RECEIVE_OBSERVING_LOG = 'RECEIVE_OBSERVING_LOG';

export const SEND_ACTION = 'SEND_ACTION';

export const REQUEST_TIME_DATA = 'REQUEST_TIME_DATA';
export const RECEIVE_TIME_DATA = 'RECEIVE_TIME_DATA';
export const CLOCK_START = 'CLOCK_START';
export const CLOCK_STOP = 'CLOCK_STOP';
export const CLOCK_TICK = 'CLOCK_TICK';

export const RECEIVE_CONTROL_LOCATION = 'RECEIVE_CONTROL_LOCATION';

export const UPDATE_TOPICS_FIELDS_INFO = 'UPDATE_TOPICS_FIELDS_INFO';

export const NIGHT_REPORT_UPDATE = 'NIGHT_REPORT_UPDATE';
export const NIGHT_REPORT_SUCCESS = 'NIGHT_REPORT_SUCCESS';
