export const REQUEST_TOKEN = 'REQUEST_TOKEN';
export const RECEIVE_TOKEN = 'RECEIVE_TOKEN';
export const REQUEST_REMOVE_TOKEN = 'REQUEST_REMOVE_TOKEN';
export const REMOVE_REMOTE_TOKEN = 'REMOVE_REMOTE_TOKEN';
export const REJECT_TOKEN = 'REJECT_TOKEN';
export const EMPTY_TOKEN = 'EMPTY_TOKEN';
export const EXPIRE_TOKEN = 'EXPIRE_TOKEN';
export const MARK_ERROR_TOKEN = 'MARK_ERROR_TOKEN';
export const MARK_ERROR_REMOVE_TOKEN = 'MARK_ERROR_REMOVE_TOKEN';
export const GET_TOKEN_FROM_LOCALSTORAGE = 'GET_TOKEN_FROM_LOCALSTORAGE';

export const OPEN_WS_CONNECTION = 'START_WS_CONNECTION';
export const CHANGE_WS_STATE = 'CHANGE_WS_STATE';
export const ADD_GROUP_SUBSCRIPTION = 'ADD_GROUP_SUBSCRIPTION';
export const RECEIVE_GROUP_CONFIRMATION_MESSAGE = 'RECEIVE_GROUP_CONFIRMATION_MESSAGE';
export const RECEIVE_GROUP_SUBSCRIPTION_DATA = 'RECEIVE_GROUP_SUBSCRIPTION_DATA';
export const REMOVE_GROUP_SUBSCRIPTION = 'REMOVE_GROUP_SUBSCRIPTION';
export const UPDATE_LAST_SAL_COMMAND = 'UPDATE_LAST_SAL_COMMAND';

export const RECEIVE_IMAGE_SEQUENCE_DATA = 'RECEIVE_IMAGE_SEQUENCE_DATA';
export const RECEIVE_CAMERA_STATE_DATA = 'RECEIVE_CAMERA_STATE_DATA';
export const RECEIVE_READOUT_DATA = 'RECEIVE_READOUT_DATA';

export const UPDATE_SCRIPT_HEARTBEAT = 'UPDATE_SCRIPT_HEARTBEAT';
export const REMOVE_SCRIPTS_HEARTBEATS = 'REMOVE_SCRIPTS_HEARTBEATS';
