export const REQUEST_TOKEN = 'REQUEST_TOKEN';
export const RECEIVE_TOKEN = 'RECEIVE_TOKEN';

export const OPEN_WS_CONNECTION = 'START_WS_CONNECTION';
export const CHANGE_WS_STATE = 'CHANGE_WS_STATE';
export const ADD_GROUP_SUBSCRIPTION = 'ADD_GROUP_SUBSCRIPTION';
export const RECEIVE_GROUP_CONFIRMATION_MESSAGE = 'RECEIVE_GROUP_CONFIRMATION_MESSAGE';
export const RECEIVE_GROUP_SUBSCRIPTION_DATA = 'RECEIVE_GROUP_SUBSCRIPTION_DATA';
export const REMOVE_GROUP_SUBSCRIPTION = 'REMOVE_GROUP_SUBSCRIPTION';

export const RECEIVE_IMAGE_SEQUENCE_DATA = 'RECEIVE_IMAGE_SEQUENCE_DATA';
export const RECEIVE_CAMERA_STATE_DATA = 'RECEIVE_CAMERA_STATE_DATA';