import React, { Component } from 'react';
import PropTypes from 'prop-types';
import DrawerMic from './Details/DrawerMic';
import Table from './Table/Table';
import RecIcon from 'components/icons/MicsIcon/Rec/RecIcon';
import PauseIcon from 'components/icons/MicsIcon/Pause/PauseIcon';
import PlayIcon from 'components/icons/MicsIcon/Play/PlayIcon';
import styles from './Mics.module.css';


const RADIOSLINK = {
  biobio: 'https://redirector.dps.live/biobiosantiago/mp3/icecast.audio',
  carolina:
    'https://jireh-1-hls-audio-us-isp.dps.live/hls-audio/716888c72e2079612211a7130f67a27d/carolina/playlist/manifest/gotardisz/audio/now/livestream1.m3u8?dpssid=b2191543965963287cd50987a&sid=ba5t1l1xb287782483663287cd509878',
  futuro: 'https://playerservices.streamtheworld.com/api/livestream-redirect/FUTUROAAC_SC',
  corazon: 'https://playerservices.streamtheworld.com/api/livestream-redirect/CORAZON_SC',
  adn:
    'https://24383.live.streamtheworld.com/ADN_SC?DIST=TuneIn&TGT=TuneIn&maxServers=2&gdpr=0&us_privacy=1YNY&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpbiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVkX3BhcnRuZXIiOnRydWUsImlhdCI6MTYzMzM5MjExNiwiaXNzIjoidGlzcnYifQ.apBDljw5PC4GQwEls0GoHYCMKg91TAZrYLziiqLdh1U',
  newSound: 'http://localhost/media/1KHz.mp3',
};

export default class Mics extends Component {
  static propTypes = {
    /* Mics's id  */
    mics: PropTypes.object,
  };

  constructor(props) {
    super(props);

    this.state = {
      currentMic: null,

      infoPlot: null,

      mics: [],

      alarms: {},

      viewInfo: false,

      play: false,

      isRecording: false,

      records: [],
    };
  }

  //Functions to microphone. /////

  componentDidMount = () => {
    let mic1 = { id: 'Microphone 1', loc: 'mainTelescope', src: RADIOSLINK.biobio };
    let mic2 = { id: 'Microphone 2', loc: 'mainTelescope', src: RADIOSLINK.carolina };
    let mic3 = { id: 'Microphone 3', loc: 'auxilaryTelescope', src: RADIOSLINK.futuro };
    let mic4 = { id: 'Microphone 4', loc: 'auxilaryTelescope', src: RADIOSLINK.corazon };
    let mic5 = { id: 'Microphone 5', loc: 'summitFacility', src: RADIOSLINK.adn };
    let mic6 = { id: 'Microphone 6', loc: 'summitFacility', src: RADIOSLINK.biobio };

    const mics = [mic1, mic2, mic3, mic4, mic5, mic6];

    this.setState({ mics: mics });
  };

  componentWillUnmount = () => {
    this.closeMicDetails();
  };

  /**
   * Function to select a mic to show in details
   * @param {*} mic to be select
   */
  selectMic = (mic) => {
    if (this.state.currentMic) {
      let { id } = this.state.currentMic;
      this.closeMicDetails();
      if (id === mic.id) return;
    }
    this.setState({ currentMic: mic, viewInfo: true });
    mic.selectMe();
  };

  /**
   * Method to set by the selected mic the necessary info to HeatMap component to plot
   * @param {*} data, info to plot
   */
  setInfoPlot = (data) => {
    this.setState({ infoPlot: data });
  };

  /**
   * Function to change the state viewInfo and open the peleeable component mic details
   */
  openFinishedList = () => {
    this.setState({
      viewInfo: true,
    });
  };

  /**
   * Function to close Mic details and set null the current mic
   */
  closeMicDetails = () => {
    if (this.state.isRecording) this.record();
    if (this.state.play) this.play();
    this.state.currentMic.selectMe();
    this.setState({ viewInfo: false, currentMic: null, infoPlot: null });
  };

  /**
   * Function to start or stop to record, using the current mic's recordFunc
   * @returns
   */
  record = () => {
    if (!this.state.currentMic) return;

    const { isRecording } = this.state;
    this.setState({ isRecording: !isRecording });
    this.state.currentMic?.recordFunc();
  };

  /**
   * Function to push a new record on records state
   * @param {*} id of the mic that push
   * @param {*} currentTime time of the record
   * @param {*} url, the blob url generated
   * @param {*} blob, the blob generated by record func
   */
  recordPush = (id, currentTime, url, blob) => {
    const newRecord = (prevRecords) => {
      prevRecords.push({ nameFile: id + '-' + currentTime.toString() + '.wav', url: url, blob: blob });
      return { records: prevRecords };
    };
    this.setState((prevState) => newRecord(prevState.records));
  };

  /**
   * Function to play o pause the current mic sound, using the current mic's recordFunc
   * @returns
   */
  play = () => {
    if (!this.state.currentMic) return;

    const { play } = this.state;
    this.setState({ play: !play });
    this.state.currentMic.playFunc();
  };

  /**
   * Function to set the volume of current mic playing, using the setVolume function of microphone component
   * @param {float} value
   * @returns
   */
  setVolume = (value) => {
    if (!this.state.currentMic) return;
    this.state.currentMic.volumeFunc(value);
  };

  render() {
    const drawerDetail = this.state.viewInfo ? styles.micDetails : styles.collapsedMicDetail;
    const svgRec = (
      <RecIcon isRecording={this.state.isRecording} className={[styles.recSVG, styles.verticalSpace].join(' ')}/>
    );
    const svgPLay = this.state.play ? (
      <PauseIcon className={styles.playSVG}></PauseIcon>
    ) : (
      <PlayIcon className={[styles.playSVG, !this.state.play ? styles.opacity : ''].join(' ')}/>
    );
    let { volume } = this.state.currentMic ?? {};
    let textPlay = this.state.play ? 'PAUSE' : 'PLAY';
    let textRec = this.state.isRecording ? 'STOP REC' : 'START REC';

    return (
      <div>
        <div className={styles.component}>
          {/* Mic Table */}
          <div className={styles.mics}>
            <Table
              mics={this.state.mics}
              selectMic={this.selectMic}
              recordPush={this.recordPush}
              setInfoPlot={this.setInfoPlot}
            ></Table>
          </div>
          <DrawerMic
            drawerDetailCss={drawerDetail}
            id={this.state.currentMic?.id}
            infoPlot={this.state.infoPlot}
            closeMicDetails={this.closeMicDetails}
            play={this.play}
            setVolume={this.setVolume}
            volume={volume}
            isPlay={this.state.play}
            record={this.record}
            records={this.state.records}
            svgPLay={svgPLay}
            svgRec={svgRec}
            textPlay={textPlay}
            textRec={textRec}
          />
        </div>
      </div>
    );
  }
}