name: VersionUpdated
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - develop
jobs:
  build:
    name: Check Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Changelog check
        run: |
          # Checkout the target branch
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          git checkout ${{ github.base_ref }}

          # Get the version before the changes
          BASE_VERSION=$(cat package.json | jq -r .version)

          # Checkout the PR branch
          git checkout -

          # Get the version after the changes
          HEAD_VERSION=$(cat package.json | jq -r .version)

          if [ "$BASE_VERSION" == "$HEAD_VERSION" ]; then
            echo "Error: Version in package.json was not updated!"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}