name: PackageVersionUpdated
on:
  pull_request:
    paths:
      - 'love/package.json'
jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check version change in package.json
      run: |
        # Checkout the target branch
        git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
        git checkout ${{ github.base_ref }}

        # Get the version before the changes
        BASE_VERSION=$(cat package.json | jq -r .version)

        # Checkout the PR branch
        git checkout -

        # Get the version after the changes
        HEAD_VERSION=$(cat package.json | jq -r .version)

        if [ "$BASE_VERSION" == "$HEAD_VERSION" ]; then
          echo "Error: Version in package.json was not updated!"
          exit 1
        fi
